export enum STEPS {
  PROTECTION_TYPE = 0,
  STRIKE_PRICE = 1,
  QUANTITY_DURATION = 2,
  AVAILABLE_CONTRACTS = 3,
  REVIEW_ACTIVATE = 4
}

export type STEPS_TYPE = STEPS.PROTECTION_TYPE | STEPS.STRIKE_PRICE | STEPS.QUANTITY_DURATION | STEPS.AVAILABLE_CONTRACTS | STEPS.REVIEW_ACTIVATE; 